### ISSUE TITLE
Add appropriate comments in code.

### ISSUE THREAD

**Issue by getsanjeev** [madc/GY-85#2]
It would be helpful if the code has good comments. Like the use of variables should be mentioned clearly.

**Comment by madc** [comment]
This repository is still a work in progress. All the code shown is more or less [pseudocode](https://en.wikipedia.org/wiki/Pseudocode), so it is only used to explain the math behind the data.

Where do you struggle? Also, PRs are apprechiated, if you find something underrepresented or missing.

**Comment by getsanjeev** [comment]
Thanks. I will come back with a PR.

**Comment by madc** [comment]
Cool man. I'll close this issue for now. Feel free to re-open anytime..
